### ISSUE TITLE
checksum error

### ISSUE THREAD

**Issue by agsmorodin** [cybertk/csonschema#11]
I am trying to install abao and get the error:

npm install -g abao
/
|
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/opt/node-v4.2.2-linux-x64/bin/node" "/opt/node-v4.2.2-linux-x64/bin/npm" "install" "-g" "abao"
npm ERR! node v4.2.2
npm ERR! npm v2.1.10

npm ERR! shasum check failed for /tmp/npm-23264-91729760/registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR! Expected: 3d345a97bad5d767f40367550ec4418ab461c424
npm ERR! Actual: 03b361ad23457ac732b568218587a2d67c584aae
npm ERR! From: https://registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! http://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /tmp/npm-debug.log

**Comment by cybertk** [comment]
Please try `npm set registry https://registry.npmjs.org/`

**Comment by cybertk** [comment]
Update the to npm 3 when invoking `npm publish` worked for me, was npm 2.11.3 

According [Travis's build log](https://travis-ci.org/cybertk/csonschema/jobs/91530378#L101), **csonschema v0.5.2** was publish with npm v2.11.3. The issue is fixed for me when using npm 3 to publish it.

Please try `npm i -g csonschema@0.5.3-beta.1`

**Comment by agsmorodin** [comment]
I have just tried to update npm, it still doesn't work:
```
[root@localhost -]# npm -v
3.4.0
[root@localhost -]# npm install -g abao
npm WARN install Couldn't install optional dependency: shasum check failed for /tmp/npm-26959-55ec7bd5/registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm WARN install Expected: 3d345a97bad5d767f40367550ec4418ab461c424
npm WARN install Actual:   03b361ad23457ac732b568218587a2d67c584aae
npm WARN install From:     https://registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
```


btw, this works fine  npm i -g csonschema@0.5.3-beta.1
but abao requires 0.5.2 version,  and I can't install it:
```
[root@localhost -]#  npm i -g csonschema@0.5.2
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/opt/node-v4.2.2-linux-x64/bin/node" "/opt/node-v4.2.2-linux-x64/bin/npm" "i" "-g" "csonschema@0.5.2"
npm ERR! node v4.2.2
npm ERR! npm  v3.4.0

npm ERR! shasum check failed for /tmp/npm-27002-b30bdf3b/registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR! Expected: 3d345a97bad5d767f40367550ec4418ab461c424
npm ERR! Actual:   03b361ad23457ac732b568218587a2d67c584aae
npm ERR! From:     https://registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-26857-8dc5becd/registry.npmjs.org/csonschema/-/npm-debug.log
```
